"""empty message

Revision ID: 1b921a26d402
Revises: 
Create Date: 2020-07-15 13:16:04.650678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b921a26d402'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usuarios_email', table_name='usuarios')
    op.drop_column('usuarios', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('email', mysql.VARCHAR(length=50), nullable=True))
    op.create_index('ix_usuarios_email', 'usuarios', ['email'], unique=True)
    # ### end Alembic commands ###
